### ISSUE TITLE
Raspberry (or other arm) compatibility?

### ISSUE THREAD

**Issue by G47S53** [natcl/node-red-contrib-streamdeck#1]
Hello,

this node is a good idea, but I can't install it on raspberry. Is it compatible with an ARM architecture?

Best regards

**Comment by natcl** [comment]
Yes, are you sure you followed the instructions for linux in the readme ?

**Comment by G47S53** [comment]
Thanks for your reply. There were missing files in my Rpi.

I execute:
sudo apt-get install libusb-1.0-0-dev
sudo apt-get install libudev-dev

With that, it's works fine.

**Comment by jmorris644** [comment]
On a pi it says "Error opening Stream Deck device Error:  No stream decks are connected". This is on the node-red start.

I did create the rules file and reloaded.

**Comment by natcl** [comment]
And you installed libusb ?

**Comment by jmorris644** [comment]
yes

**Comment by jmorris644** [comment]
Is there a device that I should be looking for? For instance, there are no USB devices in /dev

**Comment by jmorris644** [comment]
Also, I am trying it with a pi zero W as I was hoping to just hide it in the Deck's stand. I do not think it is the issue but I will try a different Pi just to make sure. The Pi W does reboot when I plug the Deck in even though I am running it with a 3A power supply.

**Comment by natcl** [comment]
What is the output of lsusb on your device with the Streamdeck connected?

**Comment by jmorris644** [comment]
how do I determine that?

**Comment by jmorris644** [comment]
```
Bus 001 Device 002: ID 0fd9:0080 Elgato Systems GmbH Stream Deck MK.2
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

**Comment by natcl** [comment]
Seems like there was an update in the upstream library to support the mk2.
I will update the node-red node today and we'll see if it fixes the issue.

**Comment by jmorris644** [comment]
Cool. I am looking at the code right now. But now knowing the structure I cannot locate what needs to be changed.

**Comment by natcl** [comment]
If all goes well it should simply be bumping the elgato-streamdeck version in package.json.
Hopefully they’re won’t be breaking changes.


--
lecaude.com 
studioimaginaire.com

**Comment by jmorris644** [comment]
LOL, sounds good.

**Comment by natcl** [comment]
Can you try installing from git and tell me if it works ?
If so I'll publish a new package:
```
npm install -g natcl/node-red-contrib-streamdeck
```

**Comment by jmorris644** [comment]
it cant find the file
```
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -2
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/natcl/node-red-contrib-streamdeck.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

**Comment by natcl** [comment]
Oh, you need to install git:
sudo apt-get install git


--
lecaude.com 
studioimaginaire.com

**Comment by jmorris644** [comment]
haha, sorry. that is funny. I had just assumed it was installed. I will report back soon...

**Comment by jmorris644** [comment]
Sorry, I am getting a build error. I am also running it with Sudo
```
prebuild-install --runtime napi || node-gyp rebuild

prebuild-install WARN install EACCES: permission denied, access '/root/.npm'
gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/root/.cache/node-gyp/14.18.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/tmp/.node-gyp"
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/node-red-contrib-streamdeck/node_modules/node-hid/build'
gyp ERR! System Linux 5.10.63+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/node-red-contrib-streamdeck/node_modules/node-hid
gyp ERR! node -v v14.18.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-hid@2.1.1 install: `prebuild-install --runtime napi || node-gyp rebuild`
npm ERR! Exit status 1
```

**Comment by jmorris644** [comment]
Do I really want to be installing it globally?

**Comment by jmorris644** [comment]
getting closer. I installed it non-globally and am getting this error when trying to use it in NR:
```
Error opening Stream Deck device TypeError: cannot open device with path 0001:0002:00
    at new HID (/home/joe/.node-red/node_modules/node-hid/nodehid.js:49:17)
    at new StreamDeckBase (/home/joe/.node-red/node_modules/node-red-contrib-streamdeck/node_modules/elgato-stream-deck/dist/models/base.js:13:23)
    at new StreamDeckGen2Base (/home/joe/.node-red/node_modules/node-red-contrib-streamdeck/node_modules/elgato-stream-deck/dist/models/base-gen2.js:10:1)
    at new StreamDeckOriginalMK2 (/home/joe/.node-red/node_modules/node-red-contrib-streamdeck/node_modules/elgato-stream-deck/dist/models/original-mk2.js:16:9)
    at openStreamDeck (/home/joe/.node-red/node_modules/node-red-contrib-streamdeck/node_modules/elgato-stream-deck/dist/index.js:84:12)
    at streamDeckInit (/home/joe/.node-red/node_modules/node-red-contrib-streamdeck/streamdeck.js:9:22)
    at new StreamDeckIn (/home/joe/.node-red/node_modules/node-red-contrib-streamdeck/streamdeck.js:25:5)
    at Object.createNode (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/util.js:87:27)
    at Flow.start (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:206:48)
    at start (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/index.js:371:33)
```

**Comment by natcl** [comment]
Locally works fine too.
Perhaps a permission issue ?
Can you try starting Node-RED with sudo ?

**Comment by jmorris644** [comment]
I run it using systemd. So I normally run it with 
```
sudo systemctl start nodered.service
```
but I just tried
```
Sudo node-red-start
```
same issue

**Comment by natcl** [comment]
Hmm I'll need to upgrade to version 5 of the library but that might take a little more time as they changed their API. Hopefully that can make it work for you... will keep you updated.

**Comment by jmorris644** [comment]
cool. thanks for the help!!

**Comment by natcl** [comment]
Can you try this version ?
`npm install --save natcl/node-red-contrib-streamdeck#mk2support`

**Comment by jmorris644** [comment]
Same problem. I noticed that the package.json still called for elgato-stream-deck 4.0.1. Should that be 5.1.2? Also, the jpeg-turbo current version is 1.1.1. Should that be updated as well?

I program in node.js but I have never created any packages so I am unsure how to change it or I would try.

**Comment by natcl** [comment]
Hmm it seems like it didn't install the correct branch, let me check.

**Comment by jmorris644** [comment]
do i need to do an uninstall first?

**Comment by natcl** [comment]
That would probably be better yes.


--
lecaude.com 
studioimaginaire.com

**Comment by jmorris644** [comment]
ok, trying again...

**Comment by jmorris644** [comment]
ok, i uninstalled and now am getting this error
```
npm WARN checkPermissions Missing write access to /home/joe/.node-red/node_modules/elgato-stream-deck
npm ERR! code ELOOP
npm ERR! syscall access
npm ERR! path /home/joe/.node-red/node_modules/elgato-stream-deck
npm ERR! errno -40
npm ERR! ELOOP: too many symbolic links encountered, access '/home/joe/.node-red/node_modules/elgato-stream-deck'
```

**Comment by natcl** [comment]
Seems like something went wrong with the permissions, perhaps something was installed with sudo ?
Can you try deleting the folder before ?


--
lecaude.com 
studioimaginaire.com

**Comment by jmorris644** [comment]
I did try deleting all 3 folders. There is an elgato-stream-deck and an @elgato-stream-deck. Plus your contrib.

**Comment by jmorris644** [comment]
Also, every folder in node_modules is owned by me and has the same mod settings

**Comment by natcl** [comment]
Hmm could you try in a new local folder to see if you get the same issue ?


--
lecaude.com 
studioimaginaire.com

**Comment by jmorris644** [comment]
sure

**Comment by jmorris644** [comment]
ok, it installed with this warning
```
> prebuild-install -r napi || cmake-js compile --target jpegturbo

npm WARN saveError ENOENT: no such file or directory, open '/home/joe/test/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/joe/test/package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.

+ node-red-contrib-streamdeck@1.0.2
added 202 packages from 256 contributors and audited 202 packages in 432.508s

```

**Comment by jmorris644** [comment]
If I can ignore the warning I will reburn the SD card and start over rather than trying to figure out the link error. This is the only purpose for this pi W.

**Comment by jmorris644** [comment]
Also, FYI, the install did not create an elgato-stream-deck. Only the @ version of it.

**Comment by natcl** [comment]
That’s normal, the package was renamed.
The log seems to say it worked, if you install node-red too in that folder and start node-red with
npx node-red -v -u .
Does the node work now ?


--
lecaude.com 
studioimaginaire.com

**Comment by jmorris644** [comment]
I did a full reinstall. Still getting error. I also did verify that the package.json is correct
```
Error opening Stream Deck device TypeError: cannot open device with path 0001:0002:00
    at new HID (/home/joe/.node-red/node_modules/node-hid/nodehid.js:49:17)
    at new NodeHIDDevice (/home/joe/.node-red/node_modules/@elgato-stream-deck/node/dist/device.js:13:23)
    at openStreamDeck (/home/joe/.node-red/node_modules/@elgato-stream-deck/node/dist/index.js:73:20)
    at streamDeckInit (/home/joe/.node-red/node_modules/node-red-contrib-streamdeck/streamdeck.js:10:24)
    at Object.<anonymous> (/home/joe/.node-red/node_modules/node-red-contrib-streamdeck/streamdeck.js:20:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
```

**Comment by jmorris644** [comment]
If it helps, the device open address is 0001:0002:00 from the error

The result from lsusb is Bus 001 Device 002: ID 0fd9:0080

**Comment by natcl** [comment]
Hmm, best thing would be that you raise an issue here:

https://github.com/julusian/node-elgato-stream-deck

Seems like the upstream library still has issues with mk2 even if they say it's supported...

**Comment by jmorris644** [comment]
ok, will do

**Comment by jmorris644** [comment]
Thanks for your help. Here is all of the info that I have gathered and tried. In the elgato-stream-deck they set the driver type to libusb with a warning:
```
 * The original StreamDeck uses packet sizes too large for the hidraw driver which is
 * the default on linux. https://github.com/node-hid/node-hid/issues/249
 */
HID.setDriverType('libusb');
```
If I do two things I can get it working. I needed to 1) chmod /dev/hidraw0 to 666 and 2) comment out the line in elgato-stream-deck that sets the device type. At this point the device will open and I can see data coming from it. But I was concerned about the warning in elgate-stream-deck. So I tried to install node-hib@0.5.7 as documented in the above issue and got tons of errors. Too many to mention. So I then tried to build node-hib with the --driver=libusb. I had to install:
```
install libudev-dev
install libusb-1.0-0-dev
install libusb-1.0-0
```
to make that build work. But it did not solve the original issue.  Is the --driver option still relevant?

So for now I am going to try and work with the above solution that is working using hidraw. Hopefully I will not run into the packet size issue.

**Comment by jmorris644** [comment]
update: After much effort I believe it may be working. The build instructions for node-hid were incorrect. After building and using the MK2 release I am getting some results. Let me do a few more days of testing and I will confirm.

**Comment by jmorris644** [comment]
Another update: If I send the output node a message that causes any sort of error I then constantly get an error response back of "Stream Deck connection issue". The only way I have found to resolve that is to restart node-red.

**Comment by natcl** [comment]
I assume that’s with the new branch ?
If so there’s still more work to do to make it more stable as the whole API is now promise based which changes some of the logic.


--
lecaude.com 
studioimaginaire.com

**Comment by jmorris644** [comment]
Yes, with the new branch. The current main branch would not work at all.

I would be more than happy to continue to help you with the new branch if you need it.

**Comment by natcl** [comment]
Sure :)
Let me just clean up the mess I did last week first :p


--
lecaude.com 
studioimaginaire.com

**Comment by jmorris644** [comment]
FYI, I can do a pull if you wish, but you need to add the following to the docs.
```
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0080", MODE:="666", GROUP="plugdev"
```

**Comment by natcl** [comment]
Can you try pulling my branch again ?
I believe I fixed the issue with the out node, if it this doesn't work, let me know what command you are executing that fails.
I also updated the readme.

**Comment by jmorris644** [comment]
I uninstalled node-red-contrib-streamdeck, node-hid, and elgato-streamdeck. I then installed the MK2 version of streamdeck. Restarted node-red. It cannot access the device on startup.

**Comment by natcl** [comment]
hmm but is this related to the tweaks you had to do to node-hid ?

**Comment by jmorris644** [comment]
No. I don't think so. Node-hid did not have a pre-built binary for ubuntu/arm8. And their build instructions were in error. Once we figured that out then node-hid does a build on install.

**Comment by natcl** [comment]
Ok what error are you getting now ?
It seems to work fine here with my mk1

**Comment by jmorris644** [comment]
I am rebooting again, by the rules that I have created it should be creating a /dev/hidraw0 and it is not. So something is going funky with the rules, I think. [the reboot did not help]

Here is what I have:
```
SUBSYSTEM=="input", GROUP="input", MODE="0666"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0080", MODE:="666", GROUP="plugdev"
KERNAL=="hidraw*", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0080", MODE:="0666", GROUP="plugdev"
```

**Comment by natcl** [comment]
Shouldn't it be KERNEL and not KERNAL ?

**Comment by jmorris644** [comment]
haha, funny. Yes, it should be. I changed it and reloaded but it still did not work. Hmmm.

**Comment by natcl** [comment]
but  you were able to make it work previously right ?

**Comment by jmorris644** [comment]
yes, last night. And my lsusb looks good too:
```
Bus 001 Device 005: ID 0fd9:0080 Elgato Systems GmbH
Bus 001 Device 004: ID 0424:7800 Microchip Technology, Inc. (formerly SMSC)
Bus 001 Device 003: ID 0424:2514 Microchip Technology, Inc. (formerly SMSC) USB 2.0 Hub
Bus 001 Device 002: ID 0424:2514 Microchip Technology, Inc. (formerly SMSC) USB 2.0 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

**Comment by jmorris644** [comment]
But by working, very intermittently.

**Comment by jmorris644** [comment]
here is the specific error text when starting NR:
```
Initialiazing Stream Deck...
Initialiazing Stream Deck...
Error opening Stream Deck device TypeError: cannot open device with path 0001:0005:00
    at new HID (/home/joe/.node-red/node_modules/node-hid/nodehid.js:49:17)
    at new NodeHIDDevice (/home/joe/.node-red/node_modules/@elgato-stream-deck/node/dist/device.js:13:23)
    at openStreamDeck (/home/joe/.node-red/node_modules/@elgato-stream-deck/node/dist/index.js:73:20)
    at streamDeckInit (/home/joe/.node-red/node_modules/node-red-contrib-streamdeck/streamdeck.js:10:32)
    at new StreamDeckIn (/home/joe/.node-red/node_modules/node-red-contrib-streamdeck/streamdeck.js:26:7)
    at Object.createNode (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/util.js:87:27)
    at Flow.start (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:206:48)
    at start (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/index.js:371:33)
```
I also did a udevadm monitor when I started NR. Here is that output:
```
KERNEL[948.200708] remove   /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.0/0003:0FD9:0080.0003/input/input2/event0 (input)
UDEV  [948.212769] remove   /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.0/0003:0FD9:0080.0003/input/input2/event0 (input)
KERNEL[948.216457] remove   /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.0/0003:0FD9:0080.0003/input/input2 (input)
KERNEL[948.216646] remove   /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.0/0003:0FD9:0080.0003/hidraw/hidraw0 (hidraw)
KERNEL[948.216777] unbind   /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.0/0003:0FD9:0080.0003 (hid)
KERNEL[948.216913] remove   /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.0/0003:0FD9:0080.0003 (hid)
KERNEL[948.217046] unbind   /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.0 (usb)
UDEV  [948.223590] remove   /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.0/0003:0FD9:0080.0003/input/input2 (input)
UDEV  [948.227171] remove   /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.0/0003:0FD9:0080.0003/hidraw/hidraw0 (hidraw)
UDEV  [948.233434] unbind   /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.0/0003:0FD9:0080.0003 (hid)
UDEV  [948.238041] remove   /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.0/0003:0FD9:0080.0003 (hid)
UDEV  [948.242965] unbind   /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.0 (usb)
```

**Comment by natcl** [comment]
Hmm from what I see it seems the Stream Deck init is happening 2 times, I'm not sure why as on my system it's doing it only once.
Can you try with a flow that has only the input or only the output ?

**Comment by jmorris644** [comment]
I had 2 flows that used the in and out nodes. 

Also, i ran the show-devices in the nod-hid/src dir and it returned an empty array. I unplugged the MK2 and plugged it back in. I now am getting the MK2 in the array.

It is starting up correctly now.

**Comment by jmorris644** [comment]
I added a 2nd IN node and am getting the open error again on NR start

I deleted the 2nd IN node and added a 2nd OUT node. NR started fine.

hope that helps.

**Comment by natcl** [comment]
I was able to reproduce on my side with 2 in nodes.
In the mean time can you use a single in node and use link nodes for you other flows ?

**Comment by jmorris644** [comment]
of course! It is NR afterall. :)

**Comment by jmorris644** [comment]
LOL, want to hear something really funny!

I was doing some debugging because the images were not showing on the buttons that I was telling it to show on. Now, to my excuse, I was only using symbols as my images. 

I finally figured out that I had the deck upside down. :) HAHA

**Comment by natcl** [comment]
Haha that doesn't help :)

**Comment by jmorris644** [comment]
I wanted to show you what I am working on. It is control for the home theater. My house is equipped with smart switches and infrared xmitters/receivers that all use MQTT commands for control. So the buttons, through node-red send the appropriate commands to the needed devices. Even IR! Working great. And the bottom right button switches between a blank set of buttons and the images that you see in the pic. Thanks for your efforts.

![20211218_155606086_iOS](https://user-images.githubusercontent.com/8661459/146647737-753f90b0-9133-4df7-90ba-556b36708b40.png)

**Comment by natcl** [comment]
Oops never got back to you !
Thanks for showing me the result and glad it worked ! :)
